name: Run tests

on:
  pull_request:
    branches:
      - main
env:
  PYTHON_VERSION: 3.9.13

jobs:
  check:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: "x64"

      - name: Install dependencies
        run: python -m venv .venv && source .venv/bin/activate && pip install -r requirements-test.txt && pip install -r requirements.txt


      - name: Run model tests
        run: source .venv/bin/activate && make model-test

      - name: Run api tests
        run: source .venv/bin/activate && make api-test